### ISSUE TITLE
Shell Page Support for PR8

### ISSUE THREAD

**Issue by adamhill** [egvijayanand/dotnet-maui-templates#22]
Now that PR8 has actual templates for MAUI, it has fully embraced the HostBuilder pattern.

Are there any pointers on how to get your Shell Page template to get instantiated correctly?

 I tried just adding the override from the [blog post announcement](https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/), but it doesnt seem to work.

FYI:  Your placeholder templates were a great help!

Thanks.

**Comment by egvijayanand** [comment]
Hello @adamhill,

Kindly add a new Shell page from the template provided, say you name it as AppShell.xaml (and its code-behind as AppShell.xaml.cs).

By design, the Shell has to contain either Flyout items or Tab items to work correctly and the order is important.

You can uncomment the relevant sections and fill in the pages (to the `ContentTemplate` attribute) that you want to be available as part of the Shell.

And, finally in the App.xaml.cs, set the MainPage to the instance of this Shell definition as described below.

```csharp
MainPage = new AppShell();
```

If you still require any clarification, let me know, will post a sample in my repo.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hello @adamhill,

Request to kindly refer to this [.NET MAUI Samples GitHub repo](https://github.com/egvijayanand/dotnet-maui-samples) for .NET MAUI Preview 8 with Shell design pattern.

Regards,
Vijay Anand E G
