### ISSUE TITLE
Support for Maui preview 13

### ISSUE THREAD

**Issue by danim-hub** [egvijayanand/dotnet-maui-templates#36]
Hi.
Maui preview 13 is out today, with support from VS 2022 17.2.0 preview 1.0.
Is there an expected date for maui 13 support?
I am using preview 12 templates, but they do not appear in the File / New Ctrl+N dialog.
Thanks for your help

**Comment by egvijayanand** [comment]
Hi @danim-hub,

Glad to hear that these templates are useful for you and that's the objective.

I'm installing the Preview 13 bits on my machine, will assess the changes, and release the updated templates at the earliest (Item templates will work as usual since they'll have less or no impact).

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @danim-hub,

To benefit users on both Windows and macOS, have released an All-in-One .NET MAUI App project template (Preview 13), that can be used from both CLI and from within VS IDE.

For more details, kindly go through this article https://egvijayanand.in/2022/02/17/all-in-one-dotnet-maui-app-project-template/

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @danim-hub,

VS extension now supports Preview 13, kindly update.

This comes preloaded with the All-in-One template without requiring any manual CLI installation of the NuGet package.

Happy coding.

Regards,
Vijay Anand E G

**Comment by danim-hub** [comment]
Thanks Vijay for your quick response, I'm already using your new templates :)
