### ISSUE TITLE
Gesture issue in Tab template

### ISSUE THREAD

**Issue by FarFlyer** [egvijayanand/dotnet-maui-templates#43]
Hello,
in the Tab template, there is the possibility to swipe left and right to change Tab.
I see that the "header" and "footer" are not updated according to the current page (i.e. scrolling right from "calendar" to "search" leave the header of the calendar page and the footer with the pages name do not change to highlight the search page)

EDIT:
I saw this issue with the property:
android:TabbedPage.ToolbarPlacement="Bottom"

With the property set to Top it works.

**Comment by egvijayanand** [comment]
Hi @FarFlyer,

Glad that you're providing feedback about the templates.

From the info provided, understood that this issue is wrt Android and updating the value to `Top` for the attached property making it work, then it's an issue in the core Maui library.

Raise an issue to the product team [here](https://github.com/dotnet/maui/issues) so that they'll address it.

Keep providing feedback to improve the template pack.

Regards,
Vijay Anand E G
